### ISSUE TITLE
NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference        at com.google.android.gms.internal.zzblq.zzc(Unknown Source)

### ISSUE THREAD

**Issue by DevUnderos** [firebase/quickstart-android#291]
After using firebase (Analytics, Cloud Messaging, Remote Config) libraries i'm having  this problem on  different os versions of android.

Issue details from Fabric.
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
       at com.google.android.gms.internal.zzblq.zzc(Unknown Source)
       at com.google.android.gms.internal.zzblq.zza(Unknown Source)
       at com.google.android.gms.internal.zzbtm.run(Unknown Source)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
```

Firebase v10.2.1

**Comment by samtstern** [comment]
@DevUnderos can you provide any more information to help debug?  What action are you users performing when this happens?  What version of the Firebase SDK are you using?

**Comment by tictacpc** [comment]
Hi all, I'm having same problem like this. my fabric was report

**Comment by spirosoik** [comment]
same error here for Android 7.0 we have seen this.

```
ko (Deobfuscated class name) com.google.android.gms.internal.ko.zzaQ
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
       at com.google.android.gms.internal.ko.zzaQ(Unknown Source)
       at com.google.android.gms.internal.ko.zzaQ(Unknown Source)
       at com.google.android.gms.internal.afv.run(Unknown Source)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:762)
```

**Comment by alexcohn** [comment]
Exactly same here, reported by Crashlytics, not reproducible in Lab. Only reported on ARM devices, but other factors: OS version, manufacturer - seem to be irrelevant.

**Comment by spirosoik** [comment]
Just to add more info it seems that it happens on application open. Also it happens at least for us for 6.0.1 and 7.0.

**Comment by alexcohn** [comment]
The classes of `com.google.android.gms.internal` are obfuscated, but from what I can derive, a **null** List can result from unsuccessful call (via **invoke()**) to `AppMeasurement.class.getDeclaredMethod("getConditionalUserProperties")`, in **zzblq.zzb(@NonNull AppMeasurement var0, @NonNull String var1)**.

**Comment by spirosoik** [comment]
Guys it's serious problem it happens more and more in the production around a huge number of crashes for each user. 

For us started after upgrading to google play services + firebase 11.0.0

**Comment by spirosoik** [comment]
@alexcohn good catch, we have enabled remote config lately in the app. Let me have a quick test on something and I will come back to you.

**Comment by spirosoik** [comment]
@alexcohn it seems that this issue occurs when you are using `RemoteConfig` and you haven't anything set it up as config parameters. If you add some parameters this will never crash again. (at least till now no errors)

But this should be fixed in any case.

**Comment by ashtrisk** [comment]
We have had a similar issue see here - https://stackoverflow.com/questions/42362024/firebase-remote-config-nullpointerexception-on-map-keyset . We were having crashes for a lot of users in released build as reported by Crashlytics. We reported it as bug to firebase and with a series of mail lasted about 15 - 20 days, firebase team accepted it is a bug in their remote config library. And we eventually have to remove Firebase remote config from our App. This happened with us about 4 months ago. They said they will fix this in the next release. We will be making another release with Remote config re-integrated. Will update if similar issue occurs with us again.

**Comment by jphw** [comment]
Experiencing the same issues in our project.
Random crashes with report like that:

>  Exception java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
> com.google.android.gms.internal.zzblq.zzc ()
> com.google.android.gms.internal.zzblq.zza ()
> com.google.android.gms.internal.zzbtm.run ()
> android.os.AsyncTask$SerialExecutor$1.run (AsyncTask.java:231)
> java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1112)
> java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:587)
> java.lang.Thread.run (Thread.java:818)

But for us this happens ONLY on Samsung devices, for some reason.
Can't say after which Firebase update exactly this has started, but if I remove Firebase from the project completely - the issues disappears.

**Comment by alexcohn** [comment]
@jphw, have you checked https://github.com/firebase/quickstart-android/issues/291#issuecomment-312294335? Maybe all you need is set up the defaults, as described in [step 2](https://firebase.google.com/docs/remote-config/#implementation_path) ?

**Comment by jphw** [comment]
@alexcohn yes, we will add the defaults to our next release and hope that it will help (it does not reproduce on our devices so we will have to test it on our users).

**Comment by eXeP** [comment]
@spirosoik Beware, this didn't fix it for me on all devices, it is still happening sometimes even with setDefaults();

**Comment by spirosoik** [comment]
@eXeP till now for us no errors at all.

**Comment by eygraber** [comment]
I've been receiving these ever since 11.0.0 (on 11.0.4 now - android version 7.1.2):

```
08-15 23:58:05.974 16308-16435/com.myapp E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
    Process: com.myapp, PID: 16308
    java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
        at com.google.android.gms.internal.in.zzc(Unknown Source)
        at com.google.android.gms.internal.in.zza(Unknown Source)
        at com.google.android.gms.internal.abf.run(Unknown Source)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
```

**Comment by ashtrisk** [comment]
Hi guys, we recently released an update for our app with remote config added back again. And we didn't get any crashes with it. I believe this issue has been solved with the latest library release for remote config.

**Comment by Devik0213** [comment]
I faced to same problem. (My app was applied firebaseVersion 11.0.2. at now)
@ashtrisk said that this problem was fixed at latest version, (it may be 11.2.0 : https://firebase.google.com/support/release-notes/android)
When I release next time, I will try to apply 11.2.0 version.

**Comment by masterleclerc** [comment]
I use firebase version 11.2.0  (core, crash, messaging, config) and I'm still having this problem:

Exception java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
com.google.android.gms.internal.zzebe.run (zzebe.java)
android.os.AsyncTask$SerialExecutor$1.run (AsyncTask.java:234)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1113)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:588)
java.lang.Thread.run (Thread.java:818)

**Comment by dirkam** [comment]
It's the same with 11.2.2 as well, crashes happen.

**Comment by pliratu** [comment]
crash happens with 11.4.2 and setting config parameters for RemoteConfig on different devices

**Comment by balachandranar** [comment]
We are also experiencing this same issue.

Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
       at com.google.android.gms.internal.in.zzc(Unknown Source)
       at com.google.android.gms.internal.in.zza(Unknown Source)
       at com.google.android.gms.internal.abf.run(Unknown Source)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:761)

**Comment by tictacpc** [comment]
Hi all, I used version 11.0.4 on Firebase and I was changed config default parameter values using Map object and don't use XML resource. It seems work and I don't see happen again.
please check with me and give me the result of you? thanks

**Comment by masterleclerc** [comment]
I used map instead of XML with 11.2.0 version and null pointer appeared.

**Comment by masterleclerc** [comment]
Any news on this? Does the error still occur?

**Comment by MohNage7** [comment]
@spirosoik do you mean remote_config_defaults file ?

**Comment by emretekin** [comment]
crash still happens with version  11.8.0

**Comment by thesurix** [comment]
It is still present in version 11.6.2:

Fatal Exception: java.lang.NullPointerException
       at com.google.android.gms.internal.zzdtm.zzcz(Unknown Source)
       at com.google.android.gms.internal.zzdtm.zzcz(Unknown Source)
       at com.google.android.gms.internal.zzevr.run(Unknown Source)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)

**Comment by emretekin** [comment]
I think this problem occurs because of console rules.
I figured out this way, 
Go to Firebase Console 
select database then select rules tab from there
and change allow read, write: if true;

The last full source of rules tab should be like bottom
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write: if true;
    }
  }
}

This is worked for me.

**Comment by masterleclerc** [comment]
NullPointerException we are talking about here is connected with with Remote Config

**Comment by Syhids** [comment]
Reproduced in 11.4.2 when calling `remoteConfig.setDefaults()` with an empty map.

**Comment by samtstern** [comment]
@Syhids could you share the exact code that reproduces this?  A full github repo I could clone/run would be amazing (if it's not too much to ask)

**Comment by alexcohn** [comment]
@samtstern we have this issue "reproduced". But **a)** the exact code is private and huge; and **b)** the crash happens for ~0.002% of our users. It happens ~2.5 times a day per affected user.

**Comment by samtstern** [comment]
Sorry when I say "reproduce" I mean some code I can run on my own machine and see the issue predictably.  That's the only way we will really be able to dive into this any further.

**Comment by alexcohn** [comment]
@samtstern this does not happen on computer. It happens on end users' smartphones, sometimes. It happens inside the Firebase SDK, in some async thread there. Please see my [analysis](https://github.com/firebase/quickstart-android/issues/291#issuecomment-312006219) of June 29, 6 months ago. I proposed an easy fix that will let us, app developers, to mitigate this problem. Are there some serious concerns about using this approach?

**Comment by samtstern** [comment]
@alexcohn we're already pursuing a fix internally (in fact I am checking to see when it will be released) but I was just hoping we could double verify it based on your code or someone else's.

As an aside, it's almost never a good idea to catch a `NullPointerException`.  Instead we need to find the `null` reference and not call any methods on it, which is what we believe our fix does.

**Comment by alexcohn** [comment]
You are right in principle; my proposal was what one can come up with looking briefly at obfuscated code of external SDK. But sometimes a quick workaround is better than six months of unhandled crashes.

**Comment by samtstern** [comment]
@alexcohn makes sense and I agree, we've taken too long to get a fix/update to everyone.  In part this was because we couldn't actually get our own tests to crash.  Hopefully will have something for you soon.

**Comment by Syhids** [comment]
@samtstern sorry, I can't share the whole project. I could try to isolate the bug if you still need it :)

**Comment by samtstern** [comment]
@Syhids thanks, don't worry about it right now. I am chasing down a few things internally and will let you know if we need to go that far!

**Comment by alexcohn** [comment]
Two more similar problems tracked on SO: https://stackoverflow.com/questions/43864774/googlesigninoptions-googleapiclient-bind-service-serviceconnection-crash and https://stackoverflow.com/questions/39315234/firebase-remote-config-nullpointer.

**Comment by ajesh-n** [comment]
Android device:Micromax, Canvas Unite 4
Android OS version: 6.0
Firebase/Play Services SDK version: 11.8.0

Crash Report details:

Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
       at com.google.android.gms.internal.zzdvs.zzc(Unknown Source)
       at com.google.android.gms.internal.zzdvs.zza(Unknown Source)
       at com.google.android.gms.internal.zzexc.run(Unknown Source)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)

**Comment by samtstern** [comment]
Just to update, we have identified the problem and the fix will come in a future release.  I will update here when that release happens.

**Comment by fenerlee1907** [comment]
Any update on this? I keep getting crash reports and I am going to need to remove Remote Config from the app unless there is an update soon. Do you have a schedule at least?

**Comment by stari4ek** [comment]
Still getting it right after
```
        FirebaseRemoteConfig
            .getInstance()
            .fetch(CACHE_EXPIRATION_SECONDS)
            .addOnCompleteListener(
                (task) -> {
                    if (task.isSuccessful()) {
                        mFirebaseRemoteConfig.activateFetched();
```
firebase 11.4.2

Device:
```
System: 3.14.29 (20171109.180937.V0928)
Sdk: 25
Device: M8SPRO
Product: q20x
Manufacturer: Amlogic
Model: Nexus M8S PRO
```

**Comment by karmazinkd** [comment]
hey guys, any updates on this?
I'm getting the same crash report on various devices, with APIs 19 - 24

 Exception java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
com.google.android.gms.internal.zzblq.zzc ()
com.google.android.gms.internal.zzblq.zza ()
com.google.android.gms.internal.zzbtm.run ()
android.os.AsyncTask$SerialExecutor$1.run (AsyncTask.java:231)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1112)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:587)
java.lang.Thread.run (Thread.java:818)


in gradle:
    compile 'com.google.firebase:firebase-core:10.2.0'
    compile 'com.google.firebase:firebase-config:10.2.0'
    compile 'com.google.firebase:firebase-messaging:10.2.0'
    compile 'com.google.firebase:firebase-database:10.2.0'
    compile 'com.google.firebase:firebase-crash:10.2.0'

target SDK 23

does it makes sense to update Firebase libs to the latest version? Or I can get even more bugs?

**Comment by alonlevylll** [comment]
Any news about this issue? I'm using firebase-11.6.0 and the issue still happens in crashlytics logs.

crash cannot be reproduced

**Comment by fabLouis** [comment]
Same crash with:
- Firebase: 11.4.2
- targetSdk: 27
- compileSdk: 27
- buildTools: 27.0.3

**Comment by masterleclerc** [comment]
@samtstern We have new release (12.0.0). Have you fixed the error? I can see no information about this in the release notes.

**Comment by MinceMan** [comment]
I've been able to see this on my debug builds and 12.0.0 seems to have fixed the problem.

**Comment by pbizannes** [comment]
I was getting this error for a long time. Then I removed:

        <meta-data android:name="com.google.android.gms.version"
            android:value="@integer/google_play_services_version" />

... from the AndroidManifest and everything worked! (I figured that since I use "apply plugin: 'com.google.gms.google-services'" at the end of my build.gradle, I might not need it)

However, I can no longer reproduce the problem, so maybe that is just co-incidence. I was using 11.8.0.

**Comment by masterleclerc** [comment]
@pbizannes I didn't use google_play_services_version meta-data in the manifest file and was experiencing the problem.

**Comment by Jossif** [comment]
@samtstern any updates regarding this fix? If this is not fixed in 12.0, is it possible to include it tot 12.0.1 please?

**Comment by dirkam** [comment]
12.0.1 still crashes.

**Comment by masterleclerc** [comment]
It is one big joke from the firebase team. One year later and the problem (big problem!) still exists. I'm glad I removed RemoteConfig a few months ago.

**Comment by thesurix** [comment]
I agree, new version has this issue, 11 users and 77 crashes in 7 days.... Is there any chance to get answer from Google devs? RemoteConfig is useless now.

**Comment by stari4ek** [comment]
It looks like I'm getting this issue only on devices which most probably don't have Google Services. For example:
* Amazon AFTN (Fire TV?)
* Nexus M8S PRO (some Chinese tv box, which most probably doesn't have proper GMS)

**Comment by fleficher** [comment]
Hi guys,

I'm facing the same problem since I've implemented Remote Config.
But, i've got a little different stacktrace : 
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.get(java.lang.Object)' on a null object reference
       at android.os.Parcel.readException(Parcel.java:1626)
       at android.os.Parcel.readException(Parcel.java:1573)
       at com.google.android.gms.internal.zzeu.zzb(Unknown Source)
       at com.google.android.gms.internal.zzbik.zza(Unknown Source)
       at com.google.android.gms.internal.zzbhr.zza(Unknown Source)
       at com.google.android.gms.internal.zzbht.zza(Unknown Source)
       at com.google.android.gms.common.api.internal.zzm.zzb(Unknown Source)
       at com.google.android.gms.common.api.internal.zzc.zza(Unknown Source)
       at com.google.android.gms.common.api.internal.zzbo.zzh(Unknown Source)
       at com.google.android.gms.common.api.internal.zzbo.zzaiw(Unknown Source)
       at com.google.android.gms.common.api.internal.zzbo.onConnected(Unknown Source)
       at com.google.android.gms.common.internal.zzac.onConnected(Unknown Source)
       at com.google.android.gms.common.internal.zzn.zzj(Unknown Source)
       at com.google.android.gms.common.internal.zze.zzakr(Unknown Source)
       at com.google.android.gms.common.internal.zzi.zzaks(Unknown Source)
       at com.google.android.gms.common.internal.zzh.handleMessage(Unknown Source)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

Using the last firebase version or using a map for defaults values instead of an xml changed nothing.

**Comment by fleficher** [comment]
@stari4ek Most of the crashes i've got are on device that have the Google Play Services installed.
Most of them have a recent version installed ( > 12.5.xxx).
I don't think it's related to that.

**Comment by samtstern** [comment]
Hi all

This should **finally** be fixed in SDK version `15.0.0`.  For everyone who was affected by this bug for so long: we apologize and will do better.  We had a number of internal mishaps that resulted in this bugfix taking forever to be deployed.  We have already circulated a postmortem internally to make sure we don't do this again.

Thank you to everyone who added their thoughts here.

**Comment by stari4ek** [comment]
And with 15.0.0 there is another one introduced:
```
Caused by java.lang.NullPointerException
Attempt to invoke virtual method 'void com.google.android.gms.internal.config.zzar.zzc(long)' on a null object reference
com.google.firebase.remoteconfig.FirebaseRemoteConfig. (Unknown Source)
com.google.firebase.remoteconfig.FirebaseRemoteConfig.getInstance (Unknown Source)
com.google.firebase.remoteconfig.FirebaseRemoteConfig.getInstance (Unknown Source)
```

never ending story

Should I create new issue here?

**Comment by samtstern** [comment]
@stari4ek yes please do create a new issue, thank you for flagging this.

**Comment by menarayanzshrestha** [comment]
I was also seraching for this solution .

LInk : https://stackoverflow.com/questions/45961045/react-native-android-error

check this out.
