### ISSUE TITLE
"Error:This Gradle plugin requires Studio 3.0 minimum"

### ISSUE THREAD

**Issue by tomaculum** [firebase/quickstart-android#294]
### Environment

  * Android Studio: 2.3.3
  * OS version: MacOS 10.12.5 (16F73)
  
#### Steps to reproduce:

  1. Install the current stable release of Android Studio.
  2. Open a _quickstart-android_ project.
  3. Try to build the project.
  
#### Observed Results:

```
Gradle 'database' project refresh failed
Error:This Gradle plugin requires Studio 3.0 minimum
```

  
#### Expected Results:

```
Information:Gradle tasks [:app:assembleDebug]
Information:BUILD SUCCESSFUL
Information:Total time: 9.89 secs
Information:0 errors
Information:0 warnings
Information:See complete output in console
```
  
#### Relevant Code:

  ```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
        mavenLocal()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.0-alpha4'
        classpath 'com.google.gms:google-services:3.1.0'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
        mavenLocal()
        google()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}  
```

### Workaround

replace 
```
        classpath 'com.android.tools.build:gradle:3.0.0-alpha4'
```
with 
```
        classpath 'com.android.tools.build:gradle:2.3.3'
```
in the projects build.gradle files.

**Comment by pharma-vie** [comment]
Error:Flavor 'main' has no flavor dimension.

**Comment by samtstern** [comment]
@tomaculum thanks for reporting this, I didn't realize updating the plugin would enforce this restriction on lower versions of Android Studio. 

I will update things to go back to using stable tools.

**Comment by samtstern** [comment]
Fixed via #295

**Comment by goussaka** [comment]
good

**Comment by Akshshr** [comment]
I can add this isn't fixed, still seeing 

'com.android.tools.build:gradle:3.0.0-beta6'

in the gradle

**Comment by samtstern** [comment]
@Akshshr I think you need to pull the latest source, I get no results for this:

```
$ find . -type f -name "build.gradle" | xargs grep beta
```

**Comment by DARIF** [comment]
Thanks it works !

**Comment by androidkotlinejava** [comment]
Error:This Gradle plugin requires Studio 3.0 minimum


same issue...
can any one tell any solution.
above not working

showing error here
dependencies {

  ****implementation** fileTree(include: ['*.jar'], dir: 'libs')**
  androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
    exclude group: 'com.android.support', module: 'support-annotations'
  })
  compile 'com.android.support:appcompat-v7:26.1.0'
  compile 'com.android.support:design:26.1.0'
  compile 'com.google.android.gms:play-services-base:10.0.1'
  compile 'com.android.support.constraint:constraint-layout:1.0.2'
  testCompile 'junit:junit:4.12'
  implementation project(':trail')
}


here is gradle project details:
buildscript {
    repositories {
      google()
        jcenter()
      maven {
        url "https://jcenter.bintray.com"
      }
    }
    dependencies {
      classpath 'com.android.tools.build:gradle:2.3.3.'
      classpath "com.jfrog.bintray.gradle:gradle-bintray-plugin:1.7.3"
      classpath 'com.github.dcendents:android-maven-gradle-plugin:2.0'
    }
}

**Comment by dr5hn** [comment]
@androidkotlinejava 

Try Replacing
`
replace
        classpath 'com.android.tools.build:gradle:3.0.0-alpha4'
with
        classpath 'com.android.tools.build:gradle:2.3.3'
`

One More Change Required

Replace `implementation` with `compile`
compile was recently [deprecated](https://www.youtube.com/watch?v=7ll-rkLCtyk&feature=youtu.be&t=29m18s) and replaced by `implementation` or `api`
