### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.net.NetworkInfo.isConnected()' on a null object reference com.google.firebase.iid.zzad.zzchr ()

### ISSUE THREAD

**Issue by opus1269** [firebase/quickstart-android#388]
* Android device: Moto G (4), LG-US996
  * Android OS version: 7.0
  * Firebase/Play Services SDK version: 11.6.0
  
I have received this in Crash Reporting in production on the above two devices. In both cases the devices were in Connection State: Disconnected

Not sure if this is during an app update or on app launch. Since the devices are disconnected I would think it would not be during an update.  

Crash Report details:

```
Exception java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4000010 (has extras) } in com.google.firebase.iid.zzae@ad32ca6
android.app.LoadedApk$ReceiverDispatcher$Args.run (LoadedApk.java:1172)
android.os.Handler.handleCallback (Handler.java:751)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:154)
android.app.ActivityThread.main (ActivityThread.java:6247)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:872)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:762)
arrow_drop_down

Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.net.NetworkInfo.isConnected()' on a null object reference
com.google.firebase.iid.zzad.zzchr ()
com.google.firebase.iid.zzae.onReceive ()
android.app.LoadedApk$ReceiverDispatcher$Args.run (LoadedApk.java:1162)
android.os.Handler.handleCallback (Handler.java:751)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:154)
android.app.ActivityThread.main (ActivityThread.java:6247)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:872)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:762)

```

**Comment by mengoni** [comment]
I've the same problem in my app, not related to a specific device or Android version.

Crashlytics reports 228 crashes on 134 users since last week, when I updated to Firebase/Play Services 11.6.0.

Yesterday I updated the libs to 11.6.2 but didn't solve the problem, my users are still experiencing the same problem.

One of the hundreds of crash report details:

```
Fatal Exception: java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4000010 launchParam=MultiScreenLaunchParams { mDisplayId=0 mFlags=0 } bqHint=1 (has extras) } in com.google.firebase.iid.f@e036af0
       at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1195)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6682)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.net.NetworkInfo.isConnected()' on a null object reference
       at com.google.firebase.iid.zzad.zzchr(Unknown Source)
       at com.google.firebase.iid.zzae.onReceive(Unknown Source)
       at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1185)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6682)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```

**Comment by samtstern** [comment]
Thank you both for the report.  I looked into the source code of the `iid` module and I don't see any calls to `isConnected()` not guarded by a null check but I will follow up with the team anyway and see what I might be missing.

**Comment by mengoni** [comment]
Thanks @samtstern!

On stackoverflow there are other developers experiencing the same issue in the last hours: [1](https://stackoverflow.com/questions/47682530/firebase-sdk-crash-on-receiving-broadcast-intents) - [2](https://stackoverflow.com/questions/47650000/android-nullpointerexception-on-networkinfo-isconnected-with-firebase)

If you need more logs/informations don't hesitate to ask.

**Comment by samtstern** [comment]
@opus1269 @mengoni thanks for reporting this!  I can confirm that we identified the issue and have a fix that will be included in the next release of the Firebase / Play services SDKs.  I can't promise an exact date, but should be before the end of the year if all goes well. 

I am going to close this issue now as there's nothing more that can be done in the context of the `quickstart-android` repo.

**Comment by amorenew** [comment]
may help
https://stackoverflow.com/questions/44692869/internet-connectivity-causes-null-pointer-exception-in-android-application

**Comment by jackcsk** [comment]
@samtstern is it fixed on Firebse 11.8.0?

**Comment by samtstern** [comment]
@opus1269 @mengoni @amorenew @jackcsk this issue is fixed in `11.8.0`

**Comment by rafid059** [comment]
Problem still persists on `11.8.0`.

    compile 'com.google.firebase:firebase-core:11.8.0'
    compile 'com.google.firebase:firebase-messaging:11.8.0'
    compile('com.crashlytics.sdk.android:crashlytics:2.7.1@aar') {
        transitive = true
    }

Device states: 100% In background

**Comment by disav1** [comment]
Same here in 11.8.0, 98% in background

**Comment by samtstern** [comment]
@rafid059 @disav1 I am surprised to hear that you're still seeing this issue in `11.8.0`.  Could either of you provide some additional crash logs?  Whatever you have would be helpful.

**Comment by disav1** [comment]
http://crashes.to/s/83b1f242773

**Comment by BrookMezgu** [comment]
Is this fixed in 12.0.0?
